# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'page_1.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1766, 1261)
        MainWindow.setStyleSheet(u"\n"
"background-color: rgb(0, 125, 0);\n"
"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-40, 310, 1841, 20))
        self.label.setStyleSheet(u"background-color: rgb(200, 187, 9); border: 3px solid #000000;")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(-40, 390, 1841, 20))
        self.label_2.setStyleSheet(u"background-color: rgb(200, 187, 9); border: 3px solid #000000;")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 340, 1761, 41))
        font = QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"\n"
"color: rgb(200, 187, 9);")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.btn_hit = QPushButton(self.centralwidget)
        self.btn_hit.setObjectName(u"btn_hit")
        self.btn_hit.setGeometry(QRect(400, 1140, 181, 101))
        font1 = QFont()
        font1.setPointSize(17)
        font1.setBold(True)
        self.btn_hit.setFont(font1)
        self.btn_hit.setStyleSheet(u"border: 3px solid #E9B82B;")
        self.btn_stand = QPushButton(self.centralwidget)
        self.btn_stand.setObjectName(u"btn_stand")
        self.btn_stand.setGeometry(QRect(600, 1140, 181, 101))
        self.btn_stand.setFont(font1)
        self.btn_stand.setStyleSheet(u"border: 3px solid #E9B82B;")
        self.btn_split = QPushButton(self.centralwidget)
        self.btn_split.setObjectName(u"btn_split")
        self.btn_split.setGeometry(QRect(1000, 1140, 181, 101))
        self.btn_split.setFont(font1)
        self.btn_split.setStyleSheet(u"border: 3px solid #E9B82B;")
        self.btn_bet = QPushButton(self.centralwidget)
        self.btn_bet.setObjectName(u"btn_bet")
        self.btn_bet.setGeometry(QRect(800, 1140, 181, 101))
        self.btn_bet.setFont(font1)
        self.btn_bet.setStyleSheet(u"border: 3px solid #E9B82B;")
        self.btn_exit = QPushButton(self.centralwidget)
        self.btn_exit.setObjectName(u"btn_exit")
        self.btn_exit.setGeometry(QRect(1400, 1140, 181, 101))
        self.btn_exit.setFont(font1)
        self.btn_exit.setStyleSheet(u"border: 3px solid #E9B82B;")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(180, 1120, 1421, 141))
        self.label_4.setStyleSheet(u"background-color: rgb(135, 68, 0); border: 3px solid #E9B82B;")
        self.txt_bet = QLineEdit(self.centralwidget)
        self.txt_bet.setObjectName(u"txt_bet")
        self.txt_bet.setGeometry(QRect(800, 1086, 181, 21))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(780, 1070, 221, 61))
        self.label_5.setStyleSheet(u"background-color: rgb(135, 68, 0); border: 3px solid #E9B82B;")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(-30, 1050, 1841, 20))
        self.label_6.setStyleSheet(u"background-color: rgb(200, 187, 9); border: 3px solid #000000;")
        self.lbl_ph11 = QLabel(self.centralwidget)
        self.lbl_ph11.setObjectName(u"lbl_ph11")
        self.lbl_ph11.setGeometry(QRect(30, 690, 181, 281))
        self.lbl_ph11.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph11.setScaledContents(True)
        self.lbl_ph16 = QLabel(self.centralwidget)
        self.lbl_ph16.setObjectName(u"lbl_ph16")
        self.lbl_ph16.setGeometry(QRect(230, 490, 181, 281))
        self.lbl_ph16.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph16.setScaledContents(True)
        self.lbl_ph15 = QLabel(self.centralwidget)
        self.lbl_ph15.setObjectName(u"lbl_ph15")
        self.lbl_ph15.setGeometry(QRect(190, 530, 181, 281))
        self.lbl_ph15.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph15.setScaledContents(True)
        self.lbl_ph14 = QLabel(self.centralwidget)
        self.lbl_ph14.setObjectName(u"lbl_ph14")
        self.lbl_ph14.setGeometry(QRect(150, 570, 181, 281))
        self.lbl_ph14.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph14.setScaledContents(True)
        self.lbl_ph13 = QLabel(self.centralwidget)
        self.lbl_ph13.setObjectName(u"lbl_ph13")
        self.lbl_ph13.setGeometry(QRect(110, 610, 181, 281))
        self.lbl_ph13.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph13.setScaledContents(True)
        self.lbl_ph12 = QLabel(self.centralwidget)
        self.lbl_ph12.setObjectName(u"lbl_ph12")
        self.lbl_ph12.setGeometry(QRect(70, 650, 181, 281))
        self.lbl_ph12.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph12.setScaledContents(True)
        self.lbl_ph21 = QLabel(self.centralwidget)
        self.lbl_ph21.setObjectName(u"lbl_ph21")
        self.lbl_ph21.setGeometry(QRect(470, 690, 181, 281))
        self.lbl_ph21.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph21.setScaledContents(True)
        self.lbl_ph23 = QLabel(self.centralwidget)
        self.lbl_ph23.setObjectName(u"lbl_ph23")
        self.lbl_ph23.setGeometry(QRect(550, 610, 181, 281))
        self.lbl_ph23.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph23.setScaledContents(True)
        self.lbl_ph24 = QLabel(self.centralwidget)
        self.lbl_ph24.setObjectName(u"lbl_ph24")
        self.lbl_ph24.setGeometry(QRect(590, 570, 181, 281))
        self.lbl_ph24.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph24.setScaledContents(True)
        self.lbl_ph25 = QLabel(self.centralwidget)
        self.lbl_ph25.setObjectName(u"lbl_ph25")
        self.lbl_ph25.setGeometry(QRect(630, 530, 181, 281))
        self.lbl_ph25.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph25.setScaledContents(True)
        self.lbl_ph26 = QLabel(self.centralwidget)
        self.lbl_ph26.setObjectName(u"lbl_ph26")
        self.lbl_ph26.setGeometry(QRect(670, 490, 181, 281))
        self.lbl_ph26.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph26.setScaledContents(True)
        self.lbl_ph22 = QLabel(self.centralwidget)
        self.lbl_ph22.setObjectName(u"lbl_ph22")
        self.lbl_ph22.setGeometry(QRect(510, 650, 181, 281))
        self.lbl_ph22.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph22.setScaledContents(True)
        self.lbl_ph31 = QLabel(self.centralwidget)
        self.lbl_ph31.setObjectName(u"lbl_ph31")
        self.lbl_ph31.setGeometry(QRect(900, 690, 181, 281))
        self.lbl_ph31.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph31.setScaledContents(True)
        self.lbl_ph33 = QLabel(self.centralwidget)
        self.lbl_ph33.setObjectName(u"lbl_ph33")
        self.lbl_ph33.setGeometry(QRect(980, 610, 181, 281))
        self.lbl_ph33.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph33.setScaledContents(True)
        self.lbl_ph34 = QLabel(self.centralwidget)
        self.lbl_ph34.setObjectName(u"lbl_ph34")
        self.lbl_ph34.setGeometry(QRect(1020, 570, 181, 281))
        self.lbl_ph34.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph34.setScaledContents(True)
        self.lbl_ph35 = QLabel(self.centralwidget)
        self.lbl_ph35.setObjectName(u"lbl_ph35")
        self.lbl_ph35.setGeometry(QRect(1060, 530, 181, 281))
        self.lbl_ph35.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph35.setScaledContents(True)
        self.lbl_ph36 = QLabel(self.centralwidget)
        self.lbl_ph36.setObjectName(u"lbl_ph36")
        self.lbl_ph36.setGeometry(QRect(1100, 490, 181, 281))
        self.lbl_ph36.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph36.setScaledContents(True)
        self.lbl_ph32 = QLabel(self.centralwidget)
        self.lbl_ph32.setObjectName(u"lbl_ph32")
        self.lbl_ph32.setGeometry(QRect(940, 650, 181, 281))
        self.lbl_ph32.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph32.setScaledContents(True)
        self.lbl_ph41 = QLabel(self.centralwidget)
        self.lbl_ph41.setObjectName(u"lbl_ph41")
        self.lbl_ph41.setGeometry(QRect(1340, 690, 181, 281))
        self.lbl_ph41.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph41.setScaledContents(True)
        self.lbl_ph43 = QLabel(self.centralwidget)
        self.lbl_ph43.setObjectName(u"lbl_ph43")
        self.lbl_ph43.setGeometry(QRect(1420, 610, 181, 281))
        self.lbl_ph43.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph43.setScaledContents(True)
        self.lbl_ph44 = QLabel(self.centralwidget)
        self.lbl_ph44.setObjectName(u"lbl_ph44")
        self.lbl_ph44.setGeometry(QRect(1460, 570, 181, 281))
        self.lbl_ph44.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph44.setScaledContents(True)
        self.lbl_ph45 = QLabel(self.centralwidget)
        self.lbl_ph45.setObjectName(u"lbl_ph45")
        self.lbl_ph45.setGeometry(QRect(1500, 530, 181, 281))
        self.lbl_ph45.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph45.setScaledContents(True)
        self.lbl_ph46 = QLabel(self.centralwidget)
        self.lbl_ph46.setObjectName(u"lbl_ph46")
        self.lbl_ph46.setGeometry(QRect(1540, 490, 181, 281))
        self.lbl_ph46.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph46.setScaledContents(True)
        self.lbl_ph42 = QLabel(self.centralwidget)
        self.lbl_ph42.setObjectName(u"lbl_ph42")
        self.lbl_ph42.setGeometry(QRect(1380, 650, 181, 281))
        self.lbl_ph42.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_ph42.setScaledContents(True)
        self.lbl_d4 = QLabel(self.centralwidget)
        self.lbl_d4.setObjectName(u"lbl_d4")
        self.lbl_d4.setGeometry(QRect(1000, 10, 181, 281))
        self.lbl_d4.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_d3 = QLabel(self.centralwidget)
        self.lbl_d3.setObjectName(u"lbl_d3")
        self.lbl_d3.setGeometry(QRect(790, 10, 181, 281))
        self.lbl_d3.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_d5 = QLabel(self.centralwidget)
        self.lbl_d5.setObjectName(u"lbl_d5")
        self.lbl_d5.setGeometry(QRect(1210, 10, 181, 281))
        self.lbl_d5.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_d2 = QLabel(self.centralwidget)
        self.lbl_d2.setObjectName(u"lbl_d2")
        self.lbl_d2.setGeometry(QRect(580, 10, 181, 281))
        self.lbl_d2.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.lbl_d1 = QLabel(self.centralwidget)
        self.lbl_d1.setObjectName(u"lbl_d1")
        self.lbl_d1.setGeometry(QRect(370, 10, 181, 281))
        self.lbl_d1.setStyleSheet(u"background-color: rgb(255, 255, 255);  border: 3px solid #000000;")
        self.label_36 = QLabel(self.centralwidget)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(150, 990, 181, 41))
        font2 = QFont()
        font2.setPointSize(15)
        font2.setBold(True)
        self.label_36.setFont(font2)
        self.label_36.setStyleSheet(u"border: 3px solid #E9B82B;\n"
"background-color: rgb(149, 0, 0);")
        self.label_36.setAlignment(Qt.AlignCenter)
        self.label_37 = QLabel(self.centralwidget)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(590, 990, 181, 41))
        self.label_37.setFont(font2)
        self.label_37.setStyleSheet(u"border: 3px solid #E9B82B;\n"
"background-color: rgb(149, 0, 0);")
        self.label_37.setAlignment(Qt.AlignCenter)
        self.label_38 = QLabel(self.centralwidget)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(1020, 990, 181, 41))
        self.label_38.setFont(font2)
        self.label_38.setStyleSheet(u"border: 3px solid #E9B82B;\n"
"background-color: rgb(149, 0, 0);")
        self.label_38.setAlignment(Qt.AlignCenter)
        self.label_39 = QLabel(self.centralwidget)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(1460, 990, 181, 41))
        self.label_39.setFont(font2)
        self.label_39.setStyleSheet(u"border: 3px solid #E9B82B;\n"
"background-color: rgb(149, 0, 0);")
        self.label_39.setAlignment(Qt.AlignCenter)
        self.btn_start = QPushButton(self.centralwidget)
        self.btn_start.setObjectName(u"btn_start")
        self.btn_start.setGeometry(QRect(200, 1140, 181, 101))
        self.btn_start.setFont(font1)
        self.btn_start.setStyleSheet(u"border: 3px solid #E9B82B;")
        self.btn_double = QPushButton(self.centralwidget)
        self.btn_double.setObjectName(u"btn_double")
        self.btn_double.setGeometry(QRect(1200, 1140, 181, 101))
        self.btn_double.setFont(font1)
        self.btn_double.setStyleSheet(u"border: 3px solid #E9B82B;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.lbl_ph41.raise_()
        self.lbl_ph42.raise_()
        self.lbl_ph31.raise_()
        self.lbl_ph32.raise_()
        self.lbl_ph21.raise_()
        self.lbl_ph22.raise_()
        self.lbl_ph23.raise_()
        self.lbl_ph24.raise_()
        self.lbl_ph25.raise_()
        self.lbl_ph26.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.btn_hit.raise_()
        self.btn_stand.raise_()
        self.btn_split.raise_()
        self.btn_bet.raise_()
        self.btn_exit.raise_()
        self.txt_bet.raise_()
        self.label_6.raise_()
        self.lbl_ph11.raise_()
        self.lbl_ph12.raise_()
        self.lbl_ph13.raise_()
        self.lbl_ph14.raise_()
        self.lbl_ph15.raise_()
        self.lbl_ph16.raise_()
        self.lbl_ph43.raise_()
        self.lbl_ph44.raise_()
        self.lbl_ph45.raise_()
        self.lbl_ph46.raise_()
        self.lbl_ph33.raise_()
        self.lbl_ph34.raise_()
        self.lbl_ph35.raise_()
        self.lbl_ph36.raise_()
        self.lbl_d4.raise_()
        self.lbl_d3.raise_()
        self.lbl_d5.raise_()
        self.lbl_d2.raise_()
        self.lbl_d1.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.btn_start.raise_()
        self.btn_double.raise_()

        self.retranslateUi(MainWindow)
        self.btn_hit.clicked.connect(MainWindow.btn_hit_a)
        self.btn_stand.clicked.connect(MainWindow.btn_stand_a)
        self.btn_bet.clicked.connect(MainWindow.btn_bet_a)
        self.btn_split.clicked.connect(MainWindow.btn_split_a)
        self.btn_exit.clicked.connect(MainWindow.btn_exit_a)
        self.btn_start.clicked.connect(MainWindow.btn_start_a)
        self.btn_double.clicked.connect(MainWindow.btn_double_a)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Page 1", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"^ Dealer ^", None))
        self.btn_hit.setText(QCoreApplication.translate("MainWindow", u"HIT", None))
        self.btn_stand.setText(QCoreApplication.translate("MainWindow", u"STAND", None))
        self.btn_split.setText(QCoreApplication.translate("MainWindow", u"SPLIT", None))
        self.btn_bet.setText(QCoreApplication.translate("MainWindow", u"BET", None))
        self.btn_exit.setText(QCoreApplication.translate("MainWindow", u"EXIT", None))
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.lbl_ph11.setText("")
        self.lbl_ph16.setText("")
        self.lbl_ph15.setText("")
        self.lbl_ph14.setText("")
        self.lbl_ph13.setText("")
        self.lbl_ph12.setText("")
        self.lbl_ph21.setText("")
        self.lbl_ph23.setText("")
        self.lbl_ph24.setText("")
        self.lbl_ph25.setText("")
        self.lbl_ph26.setText("")
        self.lbl_ph22.setText("")
        self.lbl_ph31.setText("")
        self.lbl_ph33.setText("")
        self.lbl_ph34.setText("")
        self.lbl_ph35.setText("")
        self.lbl_ph36.setText("")
        self.lbl_ph32.setText("")
        self.lbl_ph41.setText("")
        self.lbl_ph43.setText("")
        self.lbl_ph44.setText("")
        self.lbl_ph45.setText("")
        self.lbl_ph46.setText("")
        self.lbl_ph42.setText("")
        self.lbl_d4.setText("")
        self.lbl_d3.setText("")
        self.lbl_d5.setText("")
        self.lbl_d2.setText("")
        self.lbl_d1.setText("")
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Hand One", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Hand Two", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Hand Three", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Hand Four", None))
        self.btn_start.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.btn_double.setText(QCoreApplication.translate("MainWindow", u"DOUBLE", None))
    # retranslateUi

